apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-whqk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-whqk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-whqk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-whqk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-whqk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jcmw-tenant/rhtap-demo-app/hacbs-test-project-whqk@sha256:f09734e4179ebd81d84c1fdd60a73ce89b94750e71e4bdd8f60b331b08311031
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
